server:
  port: 8080

spring:
  redis:
    host: redis
    port: 6379
    password: redis_password123!

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@service-discovery:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    hostname: api-gateway

# Circuit breaker for Docker environment
resilience4j:
  circuitbreaker:
    instances:
      inventory-service:
        wait-duration-in-open-state: 30s
      order-service:
        wait-duration-in-open-state: 30s